[riscv.riscv]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_multilib]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_lp64d]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"

[riscv.rv64_lp64]
COMMON_FLAGS = "-O2 -pipe"
CHOST = "riscv64-unknown-linux-gnu"
